import { thrillerThumbnailOne } from "./images.js";

const moviesArray = [
  {
    id: 1,
    thumbnail: thrillerThumbnailOne,
    source: "https://media.w3.org/2010/05/sintel/trailer_hd.mp4",
    title: "Drishyam",
    category: "Thriller",
  },
  {
    id: 2,
    thumbnail: thrillerThumbnailOne,
    source: "https://media.w3.org/2010/05/sintel/trailer_hd.mp4",
    title: "Drishyam",
    category: "Thriller",
  },
  {
    id: 3,
    thumbnail: thrillerThumbnailOne,
    source: "https://media.w3.org/2010/05/sintel/trailer_hd.mp4",
    title: "Drishyam",
    category: "Thriller",
  },
  {
    id: 4,
    thumbnail: thrillerThumbnailOne,
    source: "https://media.w3.org/2010/05/sintel/trailer_hd.mp4",
    title: "Drishyam",
    category: "Thriller",
  },
  {
    id: 5,
    thumbnail: thrillerThumbnailOne,
    source: "https://media.w3.org/2010/05/sintel/trailer_hd.mp4",
    title: "Drishyam",
    category: "Action",
  },
  {
    id: 6,
    thumbnail: thrillerThumbnailOne,
    source: "https://media.w3.org/2010/05/sintel/trailer_hd.mp4",
    title: "Drishyam",
    category: "Action",
  },
  {
    id: 7,
    thumbnail: thrillerThumbnailOne,
    source: "https://media.w3.org/2010/05/sintel/trailer_hd.mp4",
    title: "Drishyam",
    category: "Action",
  },
  {
    id: 8,
    thumbnail: thrillerThumbnailOne,
    source: "https://media.w3.org/2010/05/sintel/trailer_hd.mp4",
    title: "Drishyam",
    category: "Action",
  },
  {
    id: 9,
    thumbnail: thrillerThumbnailOne,
    source: "https://media.w3.org/2010/05/sintel/trailer_hd.mp4",
    title: "Drishyam",
    category: "Romance",
  },
  {
    id: 10,
    thumbnail: thrillerThumbnailOne,
    source: "https://media.w3.org/2010/05/sintel/trailer_hd.mp4",
    title: "Drishyam",
    category: "Romance",
  },
  {
    id: 11,
    thumbnail: thrillerThumbnailOne,
    source: "https://media.w3.org/2010/05/sintel/trailer_hd.mp4",
    title: "Drishyam",
    category: "Romance",
  },
  {
    id: 12,
    thumbnail: thrillerThumbnailOne,
    source: "https://media.w3.org/2010/05/sintel/trailer_hd.mp4",
    title: "Drishyam",
    category: "Romance",
  },
  {
    id: 13,
    thumbnail: thrillerThumbnailOne,
    source: "https://media.w3.org/2010/05/sintel/trailer_hd.mp4",
    title: "Drishyam",
    category: "Drama",
  },
  {
    id: 14,
    thumbnail: thrillerThumbnailOne,
    source: "https://media.w3.org/2010/05/sintel/trailer_hd.mp4",
    title: "Drishyam",
    category: "Drama",
  },
  {
    id: 15,
    thumbnail: thrillerThumbnailOne,
    source: "https://media.w3.org/2010/05/sintel/trailer_hd.mp4",
    title: "Drishyam",
    category: "Drama",
  },
  {
    id: 16,
    thumbnail: thrillerThumbnailOne,
    source: "https://media.w3.org/2010/05/sintel/trailer_hd.mp4",
    title: "Drishyam",
    category: "Drama",
  },
];

export default moviesArray;
